// Офлайн-кэш «Искры Героя»
// index.html (и навигация) — network-first: обновления с хостинга доходят сразу, офлайн берётся из кэша.
// Остальное (иконки, манифест) — cache-first.
const CACHE='iskra-v15';
const ASSETS=['./','./index.html','./manifest.webmanifest','./logo-1200x500.png','./bg-start-1170x2532.jpg','./icon-180.png','./icon-192.png','./icon-512.png','./icon-1024.png','./favicon.ico','./favicon-32.png','./favicon-48.png','./og-image-1200x630.jpg','./icons/upgrade.png','./icons/upgrade-256.png','./icons/dash.png','./icons/dash-256.png','./icons/home.png','./icons/home-256.png','./icons/back.png','./icons/back-256.png','./icons/auto.png','./icons/auto-256.png','./icons/coin.png','./icons/coin-256.png','./icons/spark.png','./icons/spark-256.png','./icons/pause.png','./icons/pause-256.png','./icons/weapon-sword.png','./icons/weapon-sword-256.png','./icons/weapon-blaster.png','./icons/weapon-blaster-256.png','./icons/weapon-blades.png','./icons/weapon-blades-256.png','./icons/weapon-lightning.png','./icons/weapon-lightning-256.png','./assets/altar.webp','./assets/base.webp','./assets/boss-ash.webp','./assets/boss-ice.webp','./assets/boss-meadow.webp','./assets/boss-shroom.webp','./assets/boss-void.webp','./assets/boss-waste.webp','./assets/chest.webp','./assets/coin-drop.webp','./assets/decor-ash.webp','./assets/decor-ice.webp','./assets/decor-meadow.webp','./assets/decor-shroom.webp','./assets/decor-void.webp','./assets/decor-waste.webp','./assets/enemies.webp','./assets/fx.webp','./assets/ground-ash.webp','./assets/ground-ice.webp','./assets/ground-meadow.webp','./assets/ground-shroom.webp','./assets/ground-void.webp','./assets/ground-waste.webp','./assets/guard.webp','./assets/hero.webp','./assets/projectiles.webp','./assets/ui-btn-blue.webp','./assets/ui-btn-dark.webp','./assets/ui-btn-orange.webp','./assets/ui-card.webp','./assets/ui-chip.webp','./assets/ui-panel.webp','./assets/icons/skill-aspd-256.webp','./assets/icons/skill-aspd.webp','./assets/icons/skill-atk-256.webp','./assets/icons/skill-atk.webp','./assets/icons/skill-bag-256.webp','./assets/icons/skill-bag.webp','./assets/icons/skill-crit-256.webp','./assets/icons/skill-crit.webp','./assets/icons/skill-hp-256.webp','./assets/icons/skill-hp.webp','./assets/icons/skill-mag-256.webp','./assets/icons/skill-mag.webp','./assets/icons/skill-regen-256.webp','./assets/icons/skill-regen.webp','./assets/icons/skill-spd-256.webp','./assets/icons/skill-spd.webp','./assets/icons/tal-greed-256.webp','./assets/icons/tal-greed.webp','./assets/icons/tal-might-256.webp','./assets/icons/tal-might.webp','./assets/icons/tal-portal-256.webp','./assets/icons/tal-portal.webp','./assets/icons/tal-vital-256.webp','./assets/icons/tal-vital.webp','./assets/icons/tal-wisdom-256.webp','./assets/icons/tal-wisdom.webp'];
// каждый файл кэшируется отдельно: один 404 (например, нет favicon на хостинге) не ломает установку и офлайн
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>Promise.all(ASSETS.map(a=>c.add(a).catch(()=>{})))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
function isPage(req){const u=new URL(req.url);return req.mode==='navigate'||u.pathname.endsWith('/')||u.pathname.endsWith('/index.html')}
self.addEventListener('fetch',e=>{
  const req=e.request;if(req.method!=='GET')return;
  const sameOrigin=new URL(req.url).origin===location.origin;if(!sameOrigin)return;
  if(isPage(req)){
    e.respondWith(fetch(req,{cache:'no-store'}).then(res=>{if(res.ok){const cp=res.clone();caches.open(CACHE).then(c=>c.put('./index.html',cp))}return res})
      .catch(()=>caches.match('./index.html').then(r=>r||caches.match('./'))));
    return;
  }
  e.respondWith(caches.match(req,{ignoreSearch:true}).then(r=>r||fetch(req).then(res=>{
    if(res.ok){const cp=res.clone();caches.open(CACHE).then(c=>c.put(req,cp))}return res})));
});
